### ISSUE TITLE
Feil årstall på innlevering

### ISSUE THREAD

**Issue by kj-develops** [uit-inf-1400-2021/uit-inf-1400-2021.github.io#1]
Dato ble riktig, men årstallet avglemt i oppgaveteksten gitt! Skjønner jo at dere mener i år, men jeg benytter anledningen til å prøve å skrive min første kommentar på GitHub..! 

Kjærsti:)

**Comment by jmbjorndalen** [comment]
Hei, helt rett bruk :)  
Nå har vi fått fikset det, så da skal jeg lukke denne. 
/ JM
